extends Node

var map1_won = false
var cash = 150

####### Tower Data #######

var towerdata = {
		
	"LilDemonT1":{
		"damage": 30,
		"rof": 1,
		"range":153,
		"category":"Missile",
		"price":50 },
		
	"FireArrowsT1":{
		"damage": 45,
		"rof": 2.5,
		"range":300,
		"category":"Missile",
		"price":75 },
		
	"LavaCanonT1":{
		"damage": 100,
		"rof": 4,
		"range":255,
		"category":"Missile",
		"price":100 },
		
	"FrostT1":{
		"damage": 150,
		"rof": 3,
		"range":200,
		"category":"Projectile",
		"price":125 },
		
		"EyesT1":{
		"damage": 300,
		"rof": 6,
		"range":160,
		"category":"Missile",
		"price":200 }
}

#-----# Waves Data #-------------------------------------#

var wave_map1 =[ 
	["TinyGhost", 1.5], 
	["TinyGhost", 1.5], 
	["TinyGhost", 1.5], 
	["TinyGhost", 1.5], 
	["TinyGhost", 1.5],  
	["TinyGhost", 1.5],  
	["TinyGhost", 1.5],
	["TinyGhost", 1.5],
	["TinyGhost", 3.8], 
	["OrangeGhost", 1.0], 
	["OrangeGhost", 1.2],
	["OrangeGhost", 1.0],
	["OrangeGhost", 1.5],
	["OrangeGhost", 3.5],
	["OrangeGhost", 1.0],
	["OrangeGhost", 1.2],
	["OrangeGhost", 1.0],
	["PurpleGhost", 1.0],
	["BlueGhost", 0.5],
	["BlueGhost", 0.5],
	["BlueGhost", 0.5], 
	["BlueGhost", 2.0], 
	["OrangeGhost", 1.5], 
	["OrangeGhost", 1.5],
	["OrangeGhost", 1.5],
	["OrangeGhost", 1.5], 
	["OrangeGhost", 1.5],
	["OrangeGhost", 1.5],
	["OrangeGhost", 3.5],
	["BlueGhost", 0.3], 
	["BlueGhost", 0.3], 
	["BlueGhost", 0.3], 
	["BlueGhost", 0.3], 
	["BlueGhost", 0.3], 
	["TinyGhost", 0.5], 
	["PurpleGhost", 1.0], 
	["BlueGhost", 0.2], 
	["BlueGhost", 0.2], 
	["BlueGhost", 0.2], 
	["BlueGhost", 0.2], 
	["BlueGhost", 0.2], 
	["BlueGhost", 0.2], 
	["BlueGhost", 0.2], 
	["BlueGhost", 0.2], 
	["BlueGhost", 0.5], 
	["BlueGhost", 1.0],
	["TinyGhost", 0.5],  
	["BlueGhost", 0.3], 
	["BlueGhost", 0.3], 
	["BlueGhost", 0.3], 
	["BlueGhost", 1.0],
	["PurpleGhost", 1.0], 
	["PurpleGhost", 3.0], 
	["OrangeGhost", 1.0], 
	["BlueGhost", 0.3], 
	["BlueGhost", 0.5], 
	["BlueGhost", 0.3],
	["OrangeGhost", 1.0],
	["OrangeGhost", 0.5],
	["OrangeGhost", 1.0], 
	["PurpleGhost", 2.5], 
	["TinyGhost", 1.0],
	["PurpleGhost", 2.0], 
	["OrangeGhost", 1.0], 
	["OrangeGhost", 1.0],
	["PurpleGhost", 1.0], 
	["PurpleGhost", 1.0], 
	["PurpleGhost", 2.0], 
	["OrangeGhost", 3.5],
	["OrangeGhost", 1.0],
	["OrangeGhost", 1.0],
	["OrangeGhost", 1.0],
	["TinyGhost", 1.5],
	["OrangeGhost", 5.0],
	["TinyGhost", 1.5],
	["PurpleGhost", 5.0], 
	["BlueGhost", 0.3], 
	["BlueGhost", 0.3],
	["BlueGhost", 0.3],
	["BlueGhost", 0.3], 
	["TinyGhost", 1.5], 
	["PurpleGhost", 0.6], 
	["PurpleGhost", 1.0], 
	["PurpleGhost", 3.0], 
	["BlueGhost", 1.3], 
	["BlueGhost", 1.3], 
	["BlueGhost", 1.3], 
	["BlueGhost", 1,5],
	["OrangeGhost", 0.5],
	["BlueGhost", 1.5],
	["OrangeGhost", 0.5],
	["BlueGhost", 1.5],
	["OrangeGhost", 0.5],
	["BlueGhost", 1.5],
	["OrangeGhost", 1.5],
	["TinyGhost", 1.5],
	["BlueGhost", 2.0],
	["TinyGhost", 4.0], 
	["PurpleGhost", 2.0], 
	["PurpleGhost", 1.0], 
	["OrangeGhost", 1.5],
	["BlueGhost", 2.0],
	["TinyGhost", 1.5],  
	["EndWave" ,2.0],
	["PurpleGhost", 0.1],
	["OrangeGhost", 0.5],
	["OrangeGhost", 0.5],
	["BlueGhost", 0.5],
	["BlueGhost", 0.3],
	["OrangeGhost", 0.5],
	["OrangeGhost", 0.5],
	["OrangeGhost", 0.5],
	["OrangeGhost", 0.5],
	["BlueGhost", 0.2],
	["BlueGhost", 0.2],
	["BlueGhost", 0.2], 
	["BlueGhost", 0.2], 
	["BlueGhost", 0.2], 
	["BlueGhost", 0.2], 
	["BlueGhost", 0.2],
	["TinyGhost", 0.2], 
	["BlueGhost", 0.2], 
	["BlueGhost", 0.2], 
	["BlueGhost", 0.2], 
	["BlueGhost", 0.2], 
	["BlueGhost", 0.2],
	["BlueGhost", 0.2], 
	["OrangeGhost", 0.3],
	["OrangeGhost", 0.3],
	["OrangeGhost", 0.3], 
	["BlueGhost", 0.3], 
	["BlueGhost", 0.3],
	["BlueGhost", 0.3],
	["BlueGhost", 0.3], 
	["TinyGhost", 2.5],  
	["BlueGhost", 0.5],
	["BlueGhost", 0.2], 
	["BlueGhost", 0.2], 
	["BlueGhost", 0.2], 
	["BlueGhost", 0.2],
	["TinyGhost", 0.2], 
	["BlueGhost", 0.2], 
	["BlueGhost", 0.2], 
	["BlueGhost", 0.2], 
	["BlueGhost", 0.2], 
	["BlueGhost", 0.2],
	["BlueGhost", 0.2],
	["BlueGhost", 0.2],
	["BlueGhost", 0.2]
	]

var wave_map2 =[ 
	["TinyGhost", 0.3], 
	["TinyGhost", 0.5], 
	["TinyGhost", 0.4], 
	["TinyGhost", 0.9], 
	["TinyGhost", 0.9], 
	["TinyGhost", 0.6], 
	["TinyGhost", 0.6], 
	["TinyGhost", 0.5], 
	["TinyGhost", 0.9], 
	["TinyGhost", 0.3], 
	["PurpleGhost", 1.5], 
	["OrangeGhost", 0.2],
	["BlueGhost", 0.2],
	["BlueGhost", 0.2],
	["BlueGhost", 2.8],
	["OrangeGhost", 0.5],
	["OrangeGhost", 0.5],
	["OrangeGhost", 1.5],
	["OrangeGhost", 2.5],
	["OrangeGhost", 0.2],
	["OrangeGhost", 0.1],
	["OrangeGhost", 0.2],
	["OrangeGhost", 4.5],
	["PurpleGhost", 2.5], 
	["PurpleGhost", 2.9], 
	["BlueGhost", 0.3], 
	["BlueGhost", 0.3], 
	["BlueGhost", 0.3], 
	["BlueGhost", 0.5],
	["PurpleGhost", 1.2], 
	["OrangeGhost", 0.5],
	["OrangeGhost", 0.5],
	["OrangeGhost", 5.2],
	["OrangeGhost", 0.2],
	["OrangeGhost", 0.1],
	["OrangeGhost", 0.2],
	["OrangeGhost", 7.5],
	["PurpleGhost", 0.9], 
	["PurpleGhost", 0.9], 
	["BlueGhost", 1.3], 
	["OrangeGhost", 0.3],
	["OrangeGhost", 0.3],
	["TinyGhost", 0.5], 
	["BlueGhost", 0.3], 
	["PurpleGhost", 5.9], 
	["BlueGhost", 0.5], 
	["OrangeGhost", 0.5],
	["OrangeGhost", 0.5],
	["TinyGhost", 0.5], 
	["BlueGhost", 0.5], 
	["OrangeGhost", 5.2],
	["OrangeGhost", 0.2],
	["OrangeGhost", 0.1],
	["OrangeGhost", 0.2],
	["OrangeGhost", 7.5],
	["PurpleGhost", 0.9], 
	["PurpleGhost", 0.9], 
	["BlueGhost", 0.3], 
	["OrangeGhost", 0.3],
	["OrangeGhost", 0.3],
	["TinyGhost", 0.3], 
	["PurpleGhost", 1.0], 
	["OrangeGhost", 0.2],
	["BlueGhost", 0.2],
	["BlueGhost", 0.3], 
	["PurpleGhost", 5.9], 
	["BlueGhost", 0.5], 
	["OrangeGhost", 0.5],
	["OrangeGhost", 0.5],
	["TinyGhost", 0.5], 
	["BlueGhost", 0.5], 
	["OrangeGhost", 5.2],
	["OrangeGhost", 0.2],
	["OrangeGhost", 0.1],
	["BlueGhost", 0.5], 
	["OrangeGhost", 0.5],
	["OrangeGhost", 0.5],
	["TinyGhost", 0.5], 
	["BlueGhost", 0.5], 
	["OrangeGhost", 0.2],
	["OrangeGhost", 0.3],
	["OrangeGhost", 0.3],
	["TinyGhost", 0.5], 
	["BlueGhost", 0.3], 
	["PurpleGhost", 5.9], 
	["BlueGhost", 0.5], 
	["OrangeGhost", 0.5],
	["OrangeGhost", 0.5],
	["TinyGhost", 0.5], 
	["BlueGhost", 0.5], 
	["TinyGhost", 0.5], 
	["BlueGhost", 0.5], 
	["BlueGhost", 0.5], 
	["TinyGhost", 0.5], 
	["TinyGhost", 0.5], 
	["OrangeGhost", 0.2],
	["OrangeGhost", 0.3],
	["OrangeGhost", 0.3],
	["PurpleGhost", 5.0],   
	["OrangeGhost", 0.3],
	["OrangeGhost", 0.3], 
	["BlueGhost", 0.3],
	["TinyGhost", 0.3], 
	["BlueGhost", 0.3],
	["OrangeGhost", 0.3],
	["BlueGhost", 0.3],
	["TinyGhost", 0.3], 
	["BlueGhost", 0.3],
	["OrangeGhost", 1.5],
	["OrangeGhost", 1.5],
	["BlueGhost", 0.5],
	["TinyGhost", 1.5],  
	["BlueGhost", 0.3],
	["BlueGhost", 0.5],
	["BlueGhost", 0.3],
	["OrangeGhost", 0.5],
	["BlueGhost", 0.5],
	["BlueGhost", 0.3],
	["BlueGhost", 0.3], 
	["BlueGhost", 0.3], 
	["BlueGhost", 0.5], 
	["BlueGhost", 0.3], 
	["BlueGhost", 0.3],
	["BlueGhost", 0.3], 
	["OrangeGhost", 0.3], 
	["BlueGhost", 0.3],
	["TinyGhost", 0.3], 
	["BlueGhost", 0.3],
	["OrangeGhost", 0.3],
	["BlueGhost", 0.3],
	["BlueGhost", 0.3], 
	["BlueGhost", 0.5],
	["BlueGhost", 0.3], 
	["BlueGhost", 0.3],
	["BlueGhost", 0.3], 
	["TinyGhost", 0.3],
	["OrangeGhost", 0.3], 
	["BlueGhost", 0.5],
	["BlueGhost", 0.3],
	["BlueGhost", 0.5],
	["BlueGhost", 0.3], 
	["BlueGhost", 0.5],
	["BlueGhost", 0.3], 
	["BlueGhost", 0.3],
	["TinyGhost", 0.3],
	["BlueGhost", 0.3], 
	["BlueGhost", 0.3], 
	["BlueGhost", 0.5],
	["BlueGhost", 0.3], 
	["BlueGhost", 0.3],
	["BlueGhost", 0.3], 
	["TinyGhost", 0.3],
	["OrangeGhost", 0.3],
	["BlueGhost", 0.3],
	["BlueGhost", 0.5],
	["BlueGhost", 0.3],
	["BlueGhost", 0.5],
	["BlueGhost", 0.3],
	]
